// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wvHgHjhMZ7rRNTU5d8DBjC
// Component: MCCE7ESyYV
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_whaddup.module.css"; // plasmic-import: wvHgHjhMZ7rRNTU5d8DBjC/projectcss
import * as sty from "./PlasmicCccc.module.css"; // plasmic-import: MCCE7ESyYV/css

export const PlasmicCccc__VariantProps = new Array();

export const PlasmicCccc__ArgProps = new Array();

function PlasmicCccc__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCccc__ArgProps,
      internalVariantPropNames: PlasmicCccc__VariantProps
    });

    return PlasmicCccc__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCccc";
  } else {
    func.displayName = `PlasmicCccc.${nodeName}`;
  }
  return func;
}

export const PlasmicCccc = Object.assign(
  // Top-level PlasmicCccc renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCccc
    internalVariantProps: PlasmicCccc__VariantProps,
    internalArgProps: PlasmicCccc__ArgProps
  }
);

export default PlasmicCccc;
/* prettier-ignore-end */
